// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoice/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreatePlaceOrder struct {
	Creator     github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	SellOrderID string                                        `protobuf:"bytes,3,opt,name=sellOrderID,proto3" json:"sellOrderID,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,4,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	Price       github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,5,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price"`
}

func (m *MsgCreatePlaceOrder) Reset()         { *m = MsgCreatePlaceOrder{} }
func (m *MsgCreatePlaceOrder) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlaceOrder) ProtoMessage()    {}
func (*MsgCreatePlaceOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{0}
}
func (m *MsgCreatePlaceOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlaceOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlaceOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlaceOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlaceOrder.Merge(m, src)
}
func (m *MsgCreatePlaceOrder) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlaceOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlaceOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlaceOrder proto.InternalMessageInfo

func (m *MsgCreatePlaceOrder) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgCreatePlaceOrder) GetSellOrderID() string {
	if m != nil {
		return m.SellOrderID
	}
	return ""
}

type MsgCreatePlaceOrderResponse struct {
	PlaceOrderID string `protobuf:"bytes,1,opt,name=placeOrderID,proto3" json:"placeOrderID,omitempty"`
}

func (m *MsgCreatePlaceOrderResponse) Reset()         { *m = MsgCreatePlaceOrderResponse{} }
func (m *MsgCreatePlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlaceOrderResponse) ProtoMessage()    {}
func (*MsgCreatePlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{1}
}
func (m *MsgCreatePlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlaceOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlaceOrderResponse.Merge(m, src)
}
func (m *MsgCreatePlaceOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlaceOrderResponse proto.InternalMessageInfo

func (m *MsgCreatePlaceOrderResponse) GetPlaceOrderID() string {
	if m != nil {
		return m.PlaceOrderID
	}
	return ""
}

type MsgCreateSellOrder struct {
	Creator       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	SellInvoiceID string                                        `protobuf:"bytes,2,opt,name=sellInvoiceID,proto3" json:"sellInvoiceID,omitempty"`
	Amount        github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	SellDuration  time.Duration                                 `protobuf:"bytes,4,opt,name=sellDuration,proto3,stdduration" json:"sellDuration"`
	Price         github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,5,opt,name=price,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price"`
}

func (m *MsgCreateSellOrder) Reset()         { *m = MsgCreateSellOrder{} }
func (m *MsgCreateSellOrder) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSellOrder) ProtoMessage()    {}
func (*MsgCreateSellOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{2}
}
func (m *MsgCreateSellOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSellOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSellOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSellOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSellOrder.Merge(m, src)
}
func (m *MsgCreateSellOrder) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSellOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSellOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSellOrder proto.InternalMessageInfo

func (m *MsgCreateSellOrder) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgCreateSellOrder) GetSellInvoiceID() string {
	if m != nil {
		return m.SellInvoiceID
	}
	return ""
}

func (m *MsgCreateSellOrder) GetSellDuration() time.Duration {
	if m != nil {
		return m.SellDuration
	}
	return 0
}

type MsgCreateSellOrderResponse struct {
	OrderID string `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (m *MsgCreateSellOrderResponse) Reset()         { *m = MsgCreateSellOrderResponse{} }
func (m *MsgCreateSellOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSellOrderResponse) ProtoMessage()    {}
func (*MsgCreateSellOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{3}
}
func (m *MsgCreateSellOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSellOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSellOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSellOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSellOrderResponse.Merge(m, src)
}
func (m *MsgCreateSellOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSellOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSellOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSellOrderResponse proto.InternalMessageInfo

func (m *MsgCreateSellOrderResponse) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type MsgDeleteSellOrder struct {
	Creator     github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	SellOrderID string                                        `protobuf:"bytes,2,opt,name=sellOrderID,proto3" json:"sellOrderID,omitempty"`
}

func (m *MsgDeleteSellOrder) Reset()         { *m = MsgDeleteSellOrder{} }
func (m *MsgDeleteSellOrder) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteSellOrder) ProtoMessage()    {}
func (*MsgDeleteSellOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{4}
}
func (m *MsgDeleteSellOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteSellOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteSellOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteSellOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteSellOrder.Merge(m, src)
}
func (m *MsgDeleteSellOrder) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteSellOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteSellOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteSellOrder proto.InternalMessageInfo

func (m *MsgDeleteSellOrder) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgDeleteSellOrder) GetSellOrderID() string {
	if m != nil {
		return m.SellOrderID
	}
	return ""
}

type MsgDeleteSellOrderResponse struct {
}

func (m *MsgDeleteSellOrderResponse) Reset()         { *m = MsgDeleteSellOrderResponse{} }
func (m *MsgDeleteSellOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteSellOrderResponse) ProtoMessage()    {}
func (*MsgDeleteSellOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{5}
}
func (m *MsgDeleteSellOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteSellOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteSellOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteSellOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteSellOrderResponse.Merge(m, src)
}
func (m *MsgDeleteSellOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteSellOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteSellOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteSellOrderResponse proto.InternalMessageInfo

type MsgCreateInvoice struct {
	Creator     github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	InvoiceID   string                                        `protobuf:"bytes,2,opt,name=invoiceID,proto3" json:"invoiceID,omitempty"`
	Name        string                                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url         string                                        `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int        `protobuf:"bytes,6,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	OrigOwner   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,7,opt,name=origOwner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"origOwner,omitempty"`
	Apy         string                                        `protobuf:"bytes,8,opt,name=apy,proto3" json:"apy,omitempty"`
	IsRootOwner bool                                          `protobuf:"varint,9,opt,name=isRootOwner,proto3" json:"isRootOwner,omitempty"`
}

func (m *MsgCreateInvoice) Reset()         { *m = MsgCreateInvoice{} }
func (m *MsgCreateInvoice) String() string { return proto.CompactTextString(m) }
func (*MsgCreateInvoice) ProtoMessage()    {}
func (*MsgCreateInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{6}
}
func (m *MsgCreateInvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateInvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateInvoice.Merge(m, src)
}
func (m *MsgCreateInvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateInvoice proto.InternalMessageInfo

func (m *MsgCreateInvoice) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgCreateInvoice) GetInvoiceID() string {
	if m != nil {
		return m.InvoiceID
	}
	return ""
}

func (m *MsgCreateInvoice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateInvoice) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MsgCreateInvoice) GetOrigOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.OrigOwner
	}
	return nil
}

func (m *MsgCreateInvoice) GetApy() string {
	if m != nil {
		return m.Apy
	}
	return ""
}

func (m *MsgCreateInvoice) GetIsRootOwner() bool {
	if m != nil {
		return m.IsRootOwner
	}
	return false
}

type MsgCreateInvoiceResponse struct {
	InvoiceID string `protobuf:"bytes,1,opt,name=invoiceID,proto3" json:"invoiceID,omitempty"`
}

func (m *MsgCreateInvoiceResponse) Reset()         { *m = MsgCreateInvoiceResponse{} }
func (m *MsgCreateInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateInvoiceResponse) ProtoMessage()    {}
func (*MsgCreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{7}
}
func (m *MsgCreateInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateInvoiceResponse.Merge(m, src)
}
func (m *MsgCreateInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateInvoiceResponse proto.InternalMessageInfo

func (m *MsgCreateInvoiceResponse) GetInvoiceID() string {
	if m != nil {
		return m.InvoiceID
	}
	return ""
}

type MsgDeleteInvoice struct {
	Creator   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	OrigOwner github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=origOwner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"origOwner,omitempty"`
	Name      string                                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgDeleteInvoice) Reset()         { *m = MsgDeleteInvoice{} }
func (m *MsgDeleteInvoice) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteInvoice) ProtoMessage()    {}
func (*MsgDeleteInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{8}
}
func (m *MsgDeleteInvoice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteInvoice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteInvoice.Merge(m, src)
}
func (m *MsgDeleteInvoice) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteInvoice proto.InternalMessageInfo

func (m *MsgDeleteInvoice) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgDeleteInvoice) GetOrigOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.OrigOwner
	}
	return nil
}

func (m *MsgDeleteInvoice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgDeleteInvoiceResponse struct {
}

func (m *MsgDeleteInvoiceResponse) Reset()         { *m = MsgDeleteInvoiceResponse{} }
func (m *MsgDeleteInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteInvoiceResponse) ProtoMessage()    {}
func (*MsgDeleteInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d445ebf9790a2691, []int{9}
}
func (m *MsgDeleteInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteInvoiceResponse.Merge(m, src)
}
func (m *MsgDeleteInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteInvoiceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreatePlaceOrder)(nil), "joltify.joltifychain.invoice.MsgCreatePlaceOrder")
	proto.RegisterType((*MsgCreatePlaceOrderResponse)(nil), "joltify.joltifychain.invoice.MsgCreatePlaceOrderResponse")
	proto.RegisterType((*MsgCreateSellOrder)(nil), "joltify.joltifychain.invoice.MsgCreateSellOrder")
	proto.RegisterType((*MsgCreateSellOrderResponse)(nil), "joltify.joltifychain.invoice.MsgCreateSellOrderResponse")
	proto.RegisterType((*MsgDeleteSellOrder)(nil), "joltify.joltifychain.invoice.MsgDeleteSellOrder")
	proto.RegisterType((*MsgDeleteSellOrderResponse)(nil), "joltify.joltifychain.invoice.MsgDeleteSellOrderResponse")
	proto.RegisterType((*MsgCreateInvoice)(nil), "joltify.joltifychain.invoice.MsgCreateInvoice")
	proto.RegisterType((*MsgCreateInvoiceResponse)(nil), "joltify.joltifychain.invoice.MsgCreateInvoiceResponse")
	proto.RegisterType((*MsgDeleteInvoice)(nil), "joltify.joltifychain.invoice.MsgDeleteInvoice")
	proto.RegisterType((*MsgDeleteInvoiceResponse)(nil), "joltify.joltifychain.invoice.MsgDeleteInvoiceResponse")
}

func init() { proto.RegisterFile("invoice/tx.proto", fileDescriptor_d445ebf9790a2691) }

var fileDescriptor_d445ebf9790a2691 = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x4f, 0xd4, 0x4e,
	0x18, 0xdf, 0xd9, 0xe5, 0xad, 0x03, 0xe4, 0xbf, 0x99, 0xbf, 0x87, 0x52, 0x49, 0x77, 0xd3, 0x18,
	0xc3, 0x85, 0xa9, 0x60, 0x42, 0xf0, 0x08, 0x34, 0x9a, 0xc6, 0x10, 0x4c, 0xbd, 0x79, 0x31, 0xa5,
	0x3b, 0x94, 0x6a, 0xb7, 0xd3, 0x74, 0xba, 0xc2, 0x1e, 0x4c, 0x4c, 0xfc, 0x02, 0xc6, 0x93, 0x1f,
	0xc8, 0x03, 0x47, 0x8e, 0xc6, 0xc3, 0x6a, 0xe0, 0x0b, 0x78, 0x34, 0x9e, 0xcc, 0x4c, 0x5f, 0x68,
	0xcb, 0xaa, 0x05, 0x96, 0xd3, 0xcc, 0x3e, 0x33, 0xcf, 0xdb, 0xef, 0xf7, 0xeb, 0x33, 0x0b, 0xdb,
	0x5e, 0xf0, 0x86, 0x7a, 0x0e, 0xd1, 0xe3, 0x63, 0x1c, 0x46, 0x34, 0xa6, 0x68, 0xf9, 0x15, 0xf5,
	0x63, 0xef, 0x60, 0x88, 0xd3, 0xd5, 0x39, 0xb4, 0xbd, 0x00, 0xa7, 0xd7, 0x94, 0xa5, 0xec, 0x7e,
	0xe8, 0xdb, 0x0e, 0x79, 0x49, 0xa3, 0x1e, 0x89, 0x12, 0x47, 0x45, 0xce, 0x8e, 0x18, 0xf1, 0xfd,
	0xd2, 0xc9, 0x1d, 0x97, 0xba, 0x54, 0x6c, 0x75, 0xbe, 0x4b, 0xad, 0xaa, 0x4b, 0xa9, 0xeb, 0x13,
	0x5d, 0xfc, 0xda, 0x1f, 0x1c, 0xe8, 0xbd, 0x41, 0x64, 0xc7, 0x1e, 0x0d, 0x92, 0x73, 0xed, 0x63,
	0x13, 0xfe, 0xbf, 0xcb, 0xdc, 0x9d, 0x88, 0xd8, 0x31, 0x79, 0xc6, 0xd3, 0xed, 0xf1, 0x98, 0xe8,
	0x29, 0x9c, 0x75, 0xb8, 0x8d, 0x46, 0x32, 0xe8, 0x82, 0x95, 0x85, 0xed, 0xb5, 0x5f, 0xa3, 0xce,
	0xaa, 0xeb, 0xc5, 0x87, 0x83, 0x7d, 0xec, 0xd0, 0xbe, 0xee, 0x50, 0xd6, 0xa7, 0x2c, 0x5d, 0x56,
	0x59, 0xef, 0xb5, 0x1e, 0x0f, 0x43, 0xc2, 0xf0, 0x96, 0xe3, 0x6c, 0xf5, 0x7a, 0x11, 0x61, 0xcc,
	0xca, 0x22, 0xa0, 0x2e, 0x9c, 0xe7, 0xe5, 0x8a, 0xc8, 0xa6, 0x21, 0xb7, 0xba, 0x60, 0x45, 0xb2,
	0x8a, 0x26, 0xf4, 0x18, 0xce, 0xd8, 0x7d, 0x3a, 0x08, 0x62, 0x79, 0x4a, 0x64, 0xc3, 0x27, 0xa3,
	0x4e, 0xe3, 0xeb, 0xa8, 0x73, 0xbf, 0x46, 0x46, 0x33, 0x88, 0xad, 0xd4, 0x1b, 0x19, 0x70, 0x3a,
	0x8c, 0x3c, 0x87, 0xc8, 0xd3, 0xd7, 0x0a, 0x93, 0x38, 0x6b, 0x5b, 0xf0, 0xee, 0x18, 0x4c, 0x2c,
	0xc2, 0x42, 0x1a, 0x30, 0x82, 0x34, 0xb8, 0x10, 0xe6, 0x56, 0xd3, 0x10, 0x00, 0x49, 0x56, 0xc9,
	0xa6, 0x8d, 0x9a, 0x10, 0xe5, 0x31, 0x9e, 0x67, 0x9d, 0x4e, 0x16, 0xd6, 0x7b, 0x70, 0x91, 0x63,
	0x68, 0x26, 0x8a, 0x30, 0x0d, 0xb9, 0x29, 0x0a, 0x29, 0x1b, 0x0b, 0xd0, 0xb6, 0x6e, 0x04, 0xed,
	0x13, 0xb8, 0xc0, 0x03, 0x1b, 0xa9, 0x7e, 0x04, 0x51, 0xf3, 0xeb, 0x4b, 0x38, 0x11, 0x18, 0xce,
	0x04, 0x86, 0xb3, 0x0b, 0xdb, 0x73, 0x3c, 0xd1, 0xa7, 0x6f, 0x1d, 0x60, 0x95, 0x1c, 0x27, 0xc4,
	0xd1, 0x06, 0x54, 0x2e, 0xe3, 0x9b, 0x53, 0x24, 0xc3, 0x59, 0x5a, 0x62, 0x27, 0xfb, 0xa9, 0xbd,
	0x07, 0x82, 0x18, 0x83, 0xf8, 0xe4, 0xd6, 0x88, 0xa9, 0xe8, 0xbd, 0x79, 0x49, 0xef, 0xda, 0xb2,
	0xa8, 0xbe, 0x52, 0x44, 0x56, 0xbd, 0xf6, 0xa3, 0x09, 0xdb, 0x79, 0x73, 0x29, 0x93, 0x93, 0xad,
	0x70, 0x19, 0x4a, 0x5e, 0x45, 0x36, 0x17, 0x06, 0x84, 0xe0, 0x54, 0x60, 0xf7, 0x49, 0xfa, 0xa1,
	0x8a, 0x3d, 0x6a, 0xc3, 0xd6, 0x20, 0xf2, 0x05, 0xeb, 0x92, 0xc5, 0xb7, 0x05, 0x61, 0xcd, 0xdc,
	0x48, 0x58, 0x7b, 0x50, 0xa2, 0x91, 0xe7, 0xee, 0x1d, 0x05, 0x24, 0x92, 0x67, 0xaf, 0xdb, 0xda,
	0x45, 0x0c, 0x5e, 0xaa, 0x1d, 0x0e, 0xe5, 0xb9, 0xa4, 0x54, 0x3b, 0x1c, 0x72, 0x42, 0x3c, 0x66,
	0x51, 0x1a, 0x27, 0x49, 0xa4, 0x2e, 0x58, 0x99, 0xb3, 0x8a, 0x26, 0x6d, 0x13, 0xca, 0x55, 0xc4,
	0x73, 0x31, 0x95, 0xc0, 0x02, 0x15, 0xb0, 0xb4, 0xcf, 0x40, 0x90, 0x95, 0x70, 0x79, 0x2b, 0x64,
	0x95, 0x00, 0x6a, 0x4e, 0x00, 0xa0, 0x31, 0xfc, 0x6a, 0x8a, 0x00, 0xa0, 0xd4, 0x45, 0x06, 0xc0,
	0xfa, 0xcf, 0x29, 0xd8, 0xda, 0x65, 0x2e, 0x7a, 0x07, 0x60, 0xfb, 0xd2, 0x4b, 0xb1, 0x86, 0xff,
	0xf6, 0x96, 0xe1, 0x31, 0x83, 0x54, 0x79, 0x74, 0x65, 0x97, 0x9c, 0x8b, 0xb7, 0xf0, 0xbf, 0xea,
	0x4c, 0x7d, 0x50, 0x33, 0x5a, 0xee, 0xa1, 0x6c, 0x5e, 0xd5, 0xa3, 0x98, 0xbe, 0x3a, 0x39, 0xfe,
	0x9d, 0xbe, 0xe2, 0x51, 0x23, 0xfd, 0x1f, 0x06, 0x03, 0x3a, 0x82, 0x8b, 0xe5, 0xa1, 0x80, 0x6b,
	0x76, 0x92, 0xde, 0x57, 0x36, 0xae, 0x76, 0xbf, 0x98, 0xb8, 0x2c, 0x70, 0x5c, 0xb3, 0x87, 0xfa,
	0x89, 0xc7, 0x4a, 0x6f, 0xdb, 0x3c, 0x39, 0x53, 0xc1, 0xe9, 0x99, 0x0a, 0xbe, 0x9f, 0xa9, 0xe0,
	0xc3, 0xb9, 0xda, 0x38, 0x3d, 0x57, 0x1b, 0x5f, 0xce, 0xd5, 0xc6, 0x0b, 0xbd, 0x20, 0xff, 0x34,
	0x66, 0xb6, 0xee, 0xf0, 0xd8, 0xfa, 0xb1, 0x9e, 0xff, 0xed, 0xe2, 0xdf, 0xc2, 0xfe, 0x8c, 0x78,
	0xa2, 0x1e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x04, 0xe5, 0x74, 0x8e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreatePlaceOrder(ctx context.Context, in *MsgCreatePlaceOrder, opts ...grpc.CallOption) (*MsgCreatePlaceOrderResponse, error)
	CreateSellOrder(ctx context.Context, in *MsgCreateSellOrder, opts ...grpc.CallOption) (*MsgCreateSellOrderResponse, error)
	DeleteSellOrder(ctx context.Context, in *MsgDeleteSellOrder, opts ...grpc.CallOption) (*MsgDeleteSellOrderResponse, error)
	CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error)
	DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePlaceOrder(ctx context.Context, in *MsgCreatePlaceOrder, opts ...grpc.CallOption) (*MsgCreatePlaceOrderResponse, error) {
	out := new(MsgCreatePlaceOrderResponse)
	err := c.cc.Invoke(ctx, "/joltify.joltifychain.invoice.Msg/CreatePlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSellOrder(ctx context.Context, in *MsgCreateSellOrder, opts ...grpc.CallOption) (*MsgCreateSellOrderResponse, error) {
	out := new(MsgCreateSellOrderResponse)
	err := c.cc.Invoke(ctx, "/joltify.joltifychain.invoice.Msg/CreateSellOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteSellOrder(ctx context.Context, in *MsgDeleteSellOrder, opts ...grpc.CallOption) (*MsgDeleteSellOrderResponse, error) {
	out := new(MsgDeleteSellOrderResponse)
	err := c.cc.Invoke(ctx, "/joltify.joltifychain.invoice.Msg/DeleteSellOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateInvoice(ctx context.Context, in *MsgCreateInvoice, opts ...grpc.CallOption) (*MsgCreateInvoiceResponse, error) {
	out := new(MsgCreateInvoiceResponse)
	err := c.cc.Invoke(ctx, "/joltify.joltifychain.invoice.Msg/CreateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteInvoice(ctx context.Context, in *MsgDeleteInvoice, opts ...grpc.CallOption) (*MsgDeleteInvoiceResponse, error) {
	out := new(MsgDeleteInvoiceResponse)
	err := c.cc.Invoke(ctx, "/joltify.joltifychain.invoice.Msg/DeleteInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreatePlaceOrder(context.Context, *MsgCreatePlaceOrder) (*MsgCreatePlaceOrderResponse, error)
	CreateSellOrder(context.Context, *MsgCreateSellOrder) (*MsgCreateSellOrderResponse, error)
	DeleteSellOrder(context.Context, *MsgDeleteSellOrder) (*MsgDeleteSellOrderResponse, error)
	CreateInvoice(context.Context, *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error)
	DeleteInvoice(context.Context, *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePlaceOrder(ctx context.Context, req *MsgCreatePlaceOrder) (*MsgCreatePlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaceOrder not implemented")
}
func (*UnimplementedMsgServer) CreateSellOrder(ctx context.Context, req *MsgCreateSellOrder) (*MsgCreateSellOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSellOrder not implemented")
}
func (*UnimplementedMsgServer) DeleteSellOrder(ctx context.Context, req *MsgDeleteSellOrder) (*MsgDeleteSellOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSellOrder not implemented")
}
func (*UnimplementedMsgServer) CreateInvoice(ctx context.Context, req *MsgCreateInvoice) (*MsgCreateInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoice not implemented")
}
func (*UnimplementedMsgServer) DeleteInvoice(ctx context.Context, req *MsgDeleteInvoice) (*MsgDeleteInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInvoice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePlaceOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.joltifychain.invoice.Msg/CreatePlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePlaceOrder(ctx, req.(*MsgCreatePlaceOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSellOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSellOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSellOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.joltifychain.invoice.Msg/CreateSellOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSellOrder(ctx, req.(*MsgCreateSellOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteSellOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteSellOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteSellOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.joltifychain.invoice.Msg/DeleteSellOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteSellOrder(ctx, req.(*MsgDeleteSellOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.joltifychain.invoice.Msg/CreateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateInvoice(ctx, req.(*MsgCreateInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteInvoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joltify.joltifychain.invoice.Msg/DeleteInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteInvoice(ctx, req.(*MsgDeleteInvoice))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "joltify.joltifychain.invoice.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlaceOrder",
			Handler:    _Msg_CreatePlaceOrder_Handler,
		},
		{
			MethodName: "CreateSellOrder",
			Handler:    _Msg_CreateSellOrder_Handler,
		},
		{
			MethodName: "DeleteSellOrder",
			Handler:    _Msg_DeleteSellOrder_Handler,
		},
		{
			MethodName: "CreateInvoice",
			Handler:    _Msg_CreateInvoice_Handler,
		},
		{
			MethodName: "DeleteInvoice",
			Handler:    _Msg_DeleteInvoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/tx.proto",
}

func (m *MsgCreatePlaceOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlaceOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlaceOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.SellOrderID) > 0 {
		i -= len(m.SellOrderID)
		copy(dAtA[i:], m.SellOrderID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SellOrderID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePlaceOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlaceOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlaceOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PlaceOrderID) > 0 {
		i -= len(m.PlaceOrderID)
		copy(dAtA[i:], m.PlaceOrderID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PlaceOrderID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSellOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSellOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSellOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.SellDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.SellDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTx(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.SellInvoiceID) > 0 {
		i -= len(m.SellInvoiceID)
		copy(dAtA[i:], m.SellInvoiceID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SellInvoiceID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSellOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSellOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSellOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrderID) > 0 {
		i -= len(m.OrderID)
		copy(dAtA[i:], m.OrderID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrderID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteSellOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteSellOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteSellOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SellOrderID) > 0 {
		i -= len(m.SellOrderID)
		copy(dAtA[i:], m.SellOrderID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SellOrderID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteSellOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteSellOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteSellOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateInvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateInvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateInvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsRootOwner {
		i--
		if m.IsRootOwner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.Apy) > 0 {
		i -= len(m.Apy)
		copy(dAtA[i:], m.Apy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Apy)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.OrigOwner) > 0 {
		i -= len(m.OrigOwner)
		copy(dAtA[i:], m.OrigOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrigOwner)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InvoiceID) > 0 {
		i -= len(m.InvoiceID)
		copy(dAtA[i:], m.InvoiceID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.InvoiceID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InvoiceID) > 0 {
		i -= len(m.InvoiceID)
		copy(dAtA[i:], m.InvoiceID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.InvoiceID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteInvoice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteInvoice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteInvoice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OrigOwner) > 0 {
		i -= len(m.OrigOwner)
		copy(dAtA[i:], m.OrigOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrigOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePlaceOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SellOrderID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Price.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreatePlaceOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PlaceOrderID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateSellOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SellInvoiceID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.SellDuration)
	n += 1 + l + sovTx(uint64(l))
	l = m.Price.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCreateSellOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteSellOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SellOrderID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteSellOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateInvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.InvoiceID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.OrigOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Apy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.IsRootOwner {
		n += 2
	}
	return n
}

func (m *MsgCreateInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InvoiceID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteInvoice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OrigOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePlaceOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlaceOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlaceOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellOrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellOrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePlaceOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlaceOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlaceOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaceOrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlaceOrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSellOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSellOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSellOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellInvoiceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellInvoiceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.SellDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSellOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSellOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSellOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteSellOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteSellOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteSellOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellOrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellOrderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteSellOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteSellOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteSellOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateInvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateInvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateInvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvoiceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvoiceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigOwner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigOwner = append(m.OrigOwner[:0], dAtA[iNdEx:postIndex]...)
			if m.OrigOwner == nil {
				m.OrigOwner = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsRootOwner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsRootOwner = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvoiceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvoiceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteInvoice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteInvoice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteInvoice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigOwner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigOwner = append(m.OrigOwner[:0], dAtA[iNdEx:postIndex]...)
			if m.OrigOwner == nil {
				m.OrigOwner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
